### ISSUE TITLE
Old package separator "'" deprecated at ./t/dump.pl line 30.

### ISSUE THREAD

**Issue by mtelka** [garu/Clone#43]
Testing Clone with Perl 5.38.0 revealed this minor issue:
```
Old package separator "'" deprecated at ./t/dump.pl line 30.
```

**Comment by atoomic** [comment]
thanks for reporting the issue

**Comment by jkeenan** [comment]
The `master` branch of Clone's GH repository has this change, but no new CPAN release has been issued since October 2022.  The `'` package separator was finally pulled from perl 5 blead; this change will probably appear in dev release perl-5.41.3 very soon.  As a consequence, this distribution, which sits very high in the CPAN river, has begun to fail on CPANtesters.  See: http://www.cpantesters.org/cpan/report/c70621be-5c96-11ef-b179-cb1a840b22fd.

It probably just needs a version bump and new CPAN release.
@atoomic @garu

**Comment by garu** [comment]
Looks like @atoomic beat me to it and Clone 0.47 is already on CPAN with the fix!

**Comment by atoomic** [comment]
Yeap sorry should have ping you on it
